import type { Metadata } from "next";
import { Barlow } from 'next/font/google'
import "./globals.css";
import { ThemeProvider } from "@/components/ThemeProvider";


const barlow = Barlow({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-barlow',
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${barlow.variable}`}>
      <body className="font-barlow">{children}</body>
    </html>
  );
};